apiVersion: v1
kind: Service
metadata:
  name: concept-drift-detector
  namespace: default
  labels:
    app.kubernetes.io/name: concept-drift-detector
    app.kubernetes.io/instance: concept-drift-detector
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: ans
    app.kubernetes.io/managed-by: kubectl
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: concept-drift-detector
    app.kubernetes.io/instance: concept-drift-detector
