apiVersion: v1
kind: ServiceAccount
metadata:
  name: ans-registry
  namespace: ans-system
  labels:
    app.kubernetes.io/name: ans-registry
    app.kubernetes.io/instance: ans-registry
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: ans
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ans-registry
  labels:
    app.kubernetes.io/name: ans-registry
    app.kubernetes.io/instance: ans-registry
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: ans
    app.kubernetes.io/managed-by: kubectl
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ans-registry
  labels:
    app.kubernetes.io/name: ans-registry
    app.kubernetes.io/instance: ans-registry
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: ans
    app.kubernetes.io/managed-by: kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ans-registry
subjects:
- kind: ServiceAccount
  name: ans-registry
  namespace: ans-system
