apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-agent
  namespace: ans-demo
  labels:
    app.kubernetes.io/name: notification-agent
    app.kubernetes.io/instance: notification-agent
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: ans
    app.kubernetes.io/managed-by: kubectl
    ans.agent/name: notification-agent
    ans.agent/capability: notification
    ans.agent/provider: mlops-team
    ans.agent/version: "1.1.0"
    security.ans.io/clearance-level: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-agent
      app.kubernetes.io/instance: notification-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notification-agent
        app.kubernetes.io/instance: notification-agent
        app.kubernetes.io/version: "1.1.0"
        app.kubernetes.io/component: agent
        app.kubernetes.io/part-of: ans
        app.kubernetes.io/managed-by: kubectl
        ans.agent/name: notification-agent
        ans.agent/capability: notification
        ans.agent/provider: mlops-team
        ans.agent/version: "1.1.0"
        security.ans.io/clearance-level: "2"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: notification-agent
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: notification-agent
        image: notification-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: ANS_REGISTRY_URL
          value: "http://ans-registry.ans-system.svc.cluster.local"
        - name: ANS_CA_CERT_PATH
          value: "/etc/ans/certs/ca.crt"
        - name: ANS_AGENT_CERT_PATH
          value: "/etc/ans/certs/agent.crt"
        - name: ANS_AGENT_KEY_PATH
          value: "/etc/ans/certs/agent.key"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: certs
          mountPath: /etc/ans/certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: ans-agent-certs
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - notification-agent
              topologyKey: kubernetes.io/hostname
